### PR TITLE
tests: ensure proper cleanup of auxiliary process

### PR DESCRIPTION
**Pull request by marmarek**
Various qrexec tests create auxiliary process (service_proc) as a local
variable. In case of test failure, process cleanup isn't called and may
lead to FD leaks and breaking subsequent tests.

Fix this by always saving such process instance in self.service_proc and
cleaning it up in self.tearDown() (this code is already there).

### CODE REVIEW

**Comment by pwmarcz** [comment]
If I undestand correctly, these two tests still do not wait for the result of run_service - there is `p.stdout.read()` but no `p.wait()`.

**Comment by marmarek** [comment]
There is `self.service_proc.communicate()` in `tearDown`.

**Comment by marmarek** [comment]
Just after `self.service_proc.terminate()`

**Comment by marmarek** [comment]
hmm, wait, run_service,

**Comment by marmarek** [comment]
Yes, waiting for run_service process helped.

**Pull request merged**
