### PR TITLE
Enhance grammar in `qmemman`

### PR DESCRIPTION
**Pull request by Atrate**
I know typo/grammar-fixing PRs are usually frowned upon as "trying to get clout for contributing to X" but I've recently been spending some time in the dom0 journal and some of those strings have been irking me a bit, I don't think I'll be the only one to say that they could sound better and more professional.

### CODE REVIEW

**Comment by Atrate** [comment]
@CI  policy/qubesos/code-signing — Unable to verify (no valid key found) 

My key's been on the openpgp keyserver for quite a while:
https://keys.openpgp.org/vks/v1/by-fingerprint/55D7714B6A2812D901EA0B930A5AF8493A000A1E

**Comment by marmarek** [comment]
> My key's been on the openpgp.org keyserver for quite a while:

The key on the keyserver is expired...

**Comment by marmarek** [comment]
The one uploaded to github seems to have no expire date set at all

**Comment by Atrate** [comment]
I've reuploaded the key to keys.openpgp.org with a later expiration date, I hope I've done that correctly.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
