### PR TITLE
Move xen storage tests to own file

### PR DESCRIPTION
**Pull request by kalkin**
This is especially helpful if you want to run general storage tests + your own storage tests, without waiting for Xen storage based tests.

### CODE REVIEW

**Comment by marmarek** [comment]
It should be named storagexen or sth like this, because those are only storage tests, not overall Xen tests (which we may have in the future).

**Comment by kalkin** [comment]
@marmarek Good idea, I will do it after I'm back from the holidays and 32C3. Perhaps we will run into each other there :)

**Comment by marmarek** [comment]
On Tue, Dec 22, 2015 at 04:05:27PM -0800, kalkin wrote:
> Perhaps we will run into each other there :) 

Most likely :)

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by kalkin** [comment]
Renamed to storage_xen.py

**Comment by marmarek** [comment]
Thanks! Will merge it shortly (hopefully today...).

**Comment by marmarek** [comment]
Odd, I think I've already merged it, specially I see the commit here:
https://github.com/QubesOS/qubes-core-admin/commit/fdd618b420f312f55c57fe47e0fd39ea3c0939ab
But for some reason github didn't noticed that.

**Comment by marmarek** [comment]
Hmm, the commit has different ID, but looks pretty the same. Maybe I've done cherry-pick instead of merge... So, closing manually now.

**Pull request closed without merging**
