### PR TITLE
Kill a paused qube before system shutdown

### PR DESCRIPTION
**Pull request by alimirjamali**
fixes: https://github.com/QubesOS/qubes-issues/issues/8580

### CODE REVIEW

**Comment by marmarek** [comment]
This doesn't look right. If a qube was paused, it was likely done for a reason, it shouldn't execute anything without _explicit_ user action. Maybe kill paused qubes on shutdown instead?

**Comment by alimirjamali** [comment]
> Maybe kill paused qubes on shutdown instead?

This sounds more dangerous. What if the qube had open applications with proper auto-save on shutdown mechanism. Killing qube might lead to serious data-loss. Having said that, killing disposables might be a legitimate option.

**Comment by marmarek** [comment]
Ideally, we'd ask the user, but I don't think we have any way to do that. The autosave is one scenario, but if user wanted to interact with such a qube, why it was paused? Another scenario could be some misbehaving qube paused to limit damage - unpausing it would be very wrong here.

**Comment by alimirjamali** [comment]
So properly killing it would be the way. I will look into `libvirt_domain` to find the clean way to kill a paused domain. `libvirt_domain.shutdown()` fails to do it for suspended domains.

**Comment by marmarek** [comment]
See what qvm-kill does. BTW, I think killing should be only during system shutdown. Normal qvm-shutdown should not automatically change to killing on a paused qube but maybe show an error or some other message?

**Comment by alimirjamali** [comment]
@marmarek It is done. `qvm-pause` documentation is also updated to reflect this behaviour. Considering the fact that the existing behaviour is also indeed killing of paused qubes on shutdown, nothing is really changed here. It is only cleaner and much faster.

**Comment by alimirjamali** [comment]
> Normal qvm-shutdown should not automatically change to killing on a paused qube but maybe show an error or some other message?

Ops. Just saw this. I will work on it.

**Comment by alimirjamali** [comment]
Reason for amendment: Making Pylint happy(er)

**Comment by alimirjamali** [comment]
It appears that CI/CD is broken at the moment.

I do not have access to PipelineRetry

**Comment by alimirjamali** [comment]
OK. Codecov is advising on the necessary unittests. I have a crude idea on the required unittest. Might be wrong

**Comment by alimirjamali** [comment]
@marmarek It appears that none of the basic integration unittests are executed. I am having trouble to find the proper unittest to update for this.

**Comment by marmarek** [comment]
Integration tests are not running in gitlab-ci, they are running only in openqa, see https://www.qubes-os.org/doc/automated-tests/

**Review by marmarek — APPROVED** [review]

**Pull request merged**
