### PR TITLE
Properly suspend all VMs, not only those with PCI devices

### PR DESCRIPTION
**Pull request by marmarek**
Just pausing a VM for a host suspend breaks 'tsc' clocksource.

QubesOS/qubes-issues#7404
QubesOS/qubes-issues#2044

TODO:

- [x] test with mirage PVH
- [x] suspend (instead of pause) stubdomain too
- [x] Fix QWT to not remove xenstore entry (https://github.com/QubesOS/qubes-issues/issues/7404#issuecomment-1117611495)
- [x] https://github.com/QubesOS/qubes-issues/issues/4657

### CODE REVIEW

**Review by DemiMarie — APPROVED** [review]

**Comment by jevank** [comment]
I use this approach with exclusion for Windows VMs and tsc default clocksource. It requires excluding VMs with attached usb devices as well (use default suspend through pause) to prevent VMs from hanging. This can probably be fixed by calling qubes.SuspendPre, but I haven't tested it enough.

**Comment by marmarek** [comment]
> It also requires excluding VMs with attached usb devices as well (use default suspend through pause) to prevent VMs from hanging

You mean attached via qvm-usb, or the sys-usb VM itself?

**Comment by marmarek** [comment]
>  test with mirage PVH

@xaki23 can you check this? Just do `virsh -c xen dompmsuspend YOUR_MIRAGE_VM mem` and then `virsh -c xen dompmwakeup YOUR_MIRAGE_VM` and see if actually suspends (`xl list`) and it survives resume.

**Comment by jevank** [comment]
> You mean attached via qvm-usb, or the sys-usb VM itself?

I mean attached via qvm-usb...

**Comment by jevank** [comment]
We have some workarounds to avoid issues on suspending with USB network devices attached from sys-usb to sys-net.

But when I tested pm_suspend action it wasn't smth similar. I hope to find time to test it and get more info.

**Comment by xaki23** [comment]
> @xaki23 can you check this? Just do `virsh -c xen dompmsuspend YOUR_MIRAGE_VM mem` and then `virsh -c xen dompmwakeup YOUR_MIRAGE_VM` and see if actually suspends (`xl list`) and it survives resume.

```
[root@dom0 ~]# qvm-ls sys-mfwt
NAME      STATE    CLASS  LABEL  TEMPLATE                  NETVM
sys-mfwt  Running  AppVM  red    mirage-firewall-20221014  sys-net
[root@dom0 ~]# xl list | grep sys-mfwt
sys-mfwt                                  2955    42     1     -b----     797.5
[root@dom0 ~]# virsh -c xen dompmsuspend sys-mfwt mem
Domain sys-mfwt successfully suspended
[root@dom0 ~]# xl list | grep sys-mfwt
sys-mfwt                                  2955    42     1     -b----     797.5
[root@dom0 ~]# qvm-ls sys-mfwt
NAME      STATE      CLASS  LABEL  TEMPLATE                  NETVM
sys-mfwt  Suspended  AppVM  red    mirage-firewall-20221014  sys-net
[root@dom0 ~]# virsh -c xen dompmwakeup sys-mfwt
error: Domain sys-mfwt could not be woken up
error: internal error: Failed to resume domain '2955'

[root@dom0 ~]# qvm-ls sys-mfwt
NAME      STATE      CLASS  LABEL  TEMPLATE                  NETVM
sys-mfwt  Suspended  AppVM  red    mirage-firewall-20221014  sys-net
[root@dom0 ~]# xl list | grep sys-mfwt
sys-mfwt                                  2955    42     1     -b----     797.5
```
a) the "suspend" took a very long time.
b) there is no change in "xl list".
c) qvm-ls lists it as suspended. 
d) wakeup immediately errors out.
e) the vm is very much still working.

**Comment by marmarek** [comment]
(copying from IRC) regarding mirage, it advertises:
```
/local/domain/2955/control/shutdown = ""   (n2955)
/local/domain/2955/control/feature-poweroff = "1"   (n2955)
/local/domain/2955/control/feature-reboot = "0"   (n2955)
/local/domain/2955/control/feature-suspend = ""   (n2955)
/local/domain/2955/control/sysrq = ""   (n2955)
/local/domain/2955/control/platform-feature-multiprocessor-suspend = "1"   (n0,r2955)
/local/domain/2955/control/platform-feature-xs_reset_watches = "1"   (n0,r2955)
```

So, it advertises suspend as _not_ supported. So, libxl needs to be fixed to respect that info (and return an error early, instead of attempting and failing).

**Comment by marmarek** [comment]
With the above commits, and also:
- https://github.com/QubesOS/qubes-core-libvirt/pull/42
- https://github.com/QubesOS/qubes-vmm-xen/pull/141

Mirage firewall is properly paused.

https://github.com/QubesOS/qubes-vmm-xen/pull/141 should also workaround the PV drivers bug, but I haven't tested it yet.

**Comment by marmarek** [comment]
> [QubesOS/qubes-vmm-xen#141](https://github.com/QubesOS/qubes-vmm-xen/pull/141) should also workaround the PV drivers bug, but I haven't tested it yet.

Tested right now, and doing `virsh -c xen dompmsuspend` and `virsh -c xen dompmwakeup` twice on Windows 10 VM with QWT installed worked, both times.

**Comment by jevank** [comment]
> Tested right now, and doing virsh -c xen dompmsuspend and virsh -c xen dompmwakeup twice on Windows 10 VM with QWT installed worked, both times.

Confirm successfully suspend/resume Windows 10 with virsh (this is great!), but lid closing with this branch still freezing it... Does 'pMSuspendForDuration is equal to dompmsuspend ?..

**Comment by marmarek** [comment]
> Also should these hooks be deprecated?..

The location is really old, but nowadays they are called from systemd: https://github.com/QubesOS/qubes-core-admin-linux/blob/master/pm-utils/qubes-suspend.service
This is what prepares VMs for host suspend, so it is very much needed.

**Comment by jevank** [comment]
>  This is what prepares VMs for host suspend, so it is very much needed.

I thought that qubesd started that tasks.. not?
```
await self.run_service_for_stdio('qubes.SuspendPre',
                                                 user='root')
```

**Comment by jevank** [comment]
This calls internal.SuspendPre! Now I understand the sequence

**Comment by jevank** [comment]
The trace shows that for windows VMs suspending stops at the qubes.SuspendPre call and it looks like the VM doesn't even paused.
The strange thing is that there is no exception here, because if you call it manually, you will get an "error code 1".

**Comment by marmarek** [comment]
> The trace shows that for Windows VMs suspending stops at the qubes.SuspendPre call and it looks like the VM doesn't even paused.
> The strange thing is that there is no exception here, because if you call it manually, you will get an "error code 1".

Are you using this branch? https://github.com/QubesOS/qubes-core-admin/pull/473/commits/faf1850180aa2b4812b951da07966070630fefa4 should fix this issue

**Comment by jevank** [comment]
I'm on this branch and there no exception here.

**Comment by marmarek** [comment]
can you add additional `except` branch for broader exceptions?, like:
```
except Exception as e:
    self.log.exception("call failed")
```
if it aborts before actually suspending VM in any way, that's bad.

**Comment by marmarek** [comment]
did it went past SuspendPre qrexec call?

**Comment by jevank** [comment]
The screen is off, I can't be sure. No logs after hard reboot

**Comment by jevank** [comment]
Oh, my fault, sorry, I've made dummy.bat on Windows qubes.suspendPre with input waiting and it is breaks it all
```
@set /p= DUMMY
```

**Comment by jevank** [comment]
With additional exception 
```
...
Oct 31 16:30:37 dom0 qubesd[2074]: vm.home: call failed
Oct 31 16:30:37 dom0 qubesd[2074]: Traceback (most recent call last):
Oct 31 16:30:37 dom0 qubesd[2074]:   File "/usr/lib/python3.8/site-packages/qubes/vm/qubesvm.py", line 1393, in suspend
Oct 31 16:30:37 dom0 qubesd[2074]:     await self.run_service_for_stdio('qubes.SuspendPre',
Oct 31 16:30:37 dom0 qubesd[2074]:   File "/usr/lib/python3.8/site-packages/qubes/vm/qubesvm.py", line 1540, in run_service_for_stdio
Oct 31 16:30:37 dom0 qubesd[2074]:     raise subprocess.CalledProcessError(p.returncode,
Oct 31 16:30:37 dom0 qubesd[2074]: subprocess.CalledProcessError: Command 'qubes.SuspendPre' returned non-zero exit status 1.
Oct 31 16:30:37 dom0 qubesd[2074]: During handling of the above exception, another exception occurred:
Oct 31 16:30:37 dom0 qubesd[2074]: Traceback (most recent call last):
Oct 31 16:30:37 dom0 qubesd[2074]:   File "/usr/lib/python3.8/site-packages/qubes/vm/qubesvm.py", line 1401, in suspend
Oct 31 16:30:37 dom0 qubesd[2074]:     qubes.utils.sanitize_stderr_for_log(e.stderr))
Oct 31 16:30:37 dom0 qubesd[2074]:   File "/usr/lib/python3.8/site-packages/qubes/utils.py", line 302, in sanitize_stderr_for_log
Oct 31 16:30:37 dom0 qubesd[2074]:     stderr = b''.join(b if b in allowed_bytes else b'_'
Oct 31 16:30:37 dom0 qubesd[2074]: TypeError: sequence item 0: expected a bytes-like object, int found
...
```

And suspend ok

**Comment by marmarek** [comment]
> Oct 31 16:30:37 dom0 qubesd[2074]: TypeError: sequence item 0: expected a bytes-like object, int found

Oh... 



> Oh, my fault, sorry, I've made dummy.bat on Windows qubes.suspendPre with input waiting and it breaks it all

I'll add some timeout...

**Comment by marmarek** [comment]
Both should be fixed now.

**Comment by marmarek** [comment]
Just to confirm - two+ times, with QWT installed too?

**Comment by jevank** [comment]
Correct, Windows 10 with QWT more than one time. Right now I've only this Windows (with QWT) on test laptop, but later I could test Windows 7 and Win10 w/o QWT too.

**Comment by jevank** [comment]
Windows 7 with QWT and Windows 10 w/o QWT suspend/resume normally.

**Pull request merged**
