### PR TITLE
qvm-backup/qvm-backup-restore: Allow reading pass phrase from file or stdin

### PR DESCRIPTION
**Pull request by jgriffiths**
Passing -p/--passphrase-file uses the first line of the file passed,
or stdin if '-' is given. This works with piped input too.

Fixes 1523.

### CODE REVIEW

**Comment by marmarek** [comment]
I think this is already handled in https://github.com/marmarek/qubes-core-admin/pull/11 it looks like a duplicated ticket (1523, 1653)...
But the option with a file, not only stdin may be a better choice :)

**Comment by jgriffiths** [comment]
Looks like I need to track your repos as well as here, gah!

**Comment by Rudd-O** [comment]
First line?  Why only first line?  Randomly generated data piped into -p could give extremely low entropy based on where the newline falls.

**Comment by jgriffiths** [comment]
The password must be able to be typed in for feature parity, raw binary data is not supported.

If you want to create a random large passphrase then hex or base64 encode it before passing it in.

**Comment by Rudd-O** [comment]
Doesn't that reduce entropy?  Is it a bad idea to introduce a specific parameter for random data read from a file-like entity?

**Comment by jgriffiths** [comment]
Entropy is not affected by the encoding used to represent it, it simply takes more bytes to encode a given amount of it using a less efficient encoding. If you want to encrypt with a binary file, pass it though a binary to text filter using stdin.

**Pull request merged**
