### PR TITLE
Add domain-shutdown event

### PR DESCRIPTION
**Pull request by kalkin**

### CODE REVIEW

**Comment by marmarek** [comment]
This is far not the only situation when domain is shut down. For example `vm.kill` is not covered. But more importantly - domain shutting down itself (`sudo poweroff` from inside). For this we need some libvirt hook (I bet I've mentioned it somewhere already, it's available only in libvirt 2.2.0+).

**Comment by kalkin** [comment]
Why does `QubesVM.shutdown` accepts the parameter `force`, but it's never actually used? Should it be removed?

**Comment by kalkin** [comment]
Or may be the `force` paramter should only be used for the events, to differentiate between a kill and normal shutdown?

**Comment by marmarek** [comment]
Implemented as libvirt even handler instead (https://github.com/marmarek/qubes-core-admin/commit/4f29e8ddba506aaaf94f71f581d1ad03ff5960b7)

**Pull request closed without merging**
