### PR TITLE
Srcrpm

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by fepitre** [comment]
@marmarek: I don't understand why this one is not working. It builds fine from my side.

**Comment by marmarek** [comment]
You can temporarily add `DEBUG=1` to .travis.yml, so we'll see output from `create-archive` script.

**Comment by fepitre** [comment]
Travis is sick no? :)

**Comment by marmarek** [comment]
Strange, I see no difference. query-spec is called few times to get archive name, but no output from create-archive...

**Comment by fepitre** [comment]
Is it normal that there is not the debug info in the log?

**Comment by marmarek** [comment]
No, I guess the script wasn't called at all. Maybe query-spec failed?

**Comment by fepitre** [comment]
I don't understand why on this one.

**Comment by marmarek** [comment]
Look what I've found:
https://travis-ci.org/marmarek/qubes-core-admin/jobs/362254620#L4257-L4260
```
+rpm -q --qf '%{NAME}-%{VERSION}.tar.gz\n' --specfile qubes-src/core-admin/rpm_spec/core-dom0.spec
error: parse error in expression
error: qubes-src/core-admin/rpm_spec/core-dom0.spec:26: bad %if condition
error: query of specfile qubes-src/core-admin/rpm_spec/core-dom0.spec failed, can't parse
```
(removed 2>/dev/null in query-spec to get this)

**Pull request merged**
