### PR TITLE
Do not remove VMs installed via rpm

### PR DESCRIPTION
**Pull request by tasket**

### CODE REVIEW

**Comment by marmarek** [comment]
Hmm, for some reason travis have not noticed this pull request...

**Comment by marmarek** [comment]
Oh, the reason (according to travis) is: "Abuse detected"
wat?!

**Comment by marmarek** [comment]
I sent an email to travis support.

**Comment by tasket** [comment]
I'm curious what it considers "abuse".

**Comment by marmarek** [comment]
@tasket I've received answer from travis support - logging in at https://travis-ci.org (then close and reopen PR) should help...

**Comment by tasket** [comment]
After login their UI has a message saying "The account ttasket has been flagged for potential abuse. Please contact support@travis-ci.com." That is the original spelling of my account name.

**Comment by tasket** [comment]
I'll try closing and re-opening as you suggest...

**Comment by tasket** [comment]
@marmarek @BanzaiMan - Logging into @travis-ci system had the effect of re-issuing the "abuse" flag, this time for user "tasket". Made the problem worse?

**Comment by tasket** [comment]
Travis support has cleared up the false positive flag on my account.

**Pull request merged**
