### PR TITLE
Extend clipboard tests

### PR DESCRIPTION
**Pull request by marmarek**
QubesOS/qubes-issues#9296

### CODE REVIEW

**Comment by marmarek** [comment]
FYI @alimirjamali I extended clipboard tests to check few more sizes. I consider adding also one above 256k, but not sure if that's necessary. This should cover testing new version. Interaction of new gui-daemon with old gui-agent needs to be tested manually.
And also, those tests do not check if notification on failure is properly displayed.

**Comment by alimirjamali** [comment]
> FYI @alimirjamali I extended clipboard tests to check few more sizes. I consider adding also one above 256k, but not sure if that's necessary. This should cover testing new version. Interaction of new gui-daemon with old gui-agent needs to be tested manually. And also, those tests do not check if notification on failure is properly displayed.

That is very nice. The test for above 256k will be necessary. Rejecting INCR is easy and could be easily added (after I could finish the existing PR).

**Comment by alimirjamali** [comment]
There should be a unittest where inter-vm shared clipboard content is over 65000 (from a Protocol 1.8 aware VM) and user tries to paste it to a VM with protocol 1.7 with 65000 character limit. xside should handle this gracefully.

**Comment by marmarek** [comment]
> There should be a unittest where inter-vm shared clipboard content is over 65000 (from a Protocol 1.8 aware VM) and user tries to paste it to a VM with protocol 1.7 with 65000 character limit. xside should handle this gracefully.

There seems to be no difference in the paste path between versions, so I expect the current test (200k) to cover this case already.

**Comment by alimirjamali** [comment]
> There seems to be no difference in the paste path between versions, so I expect the current test (200k) to cover this case already.

OK. So no forced limit from the xside to vmside. Makes very sense. Better to keep it this way (now that I reconsider it).

**Pull request merged**
