### PR TITLE
Fix "file pool cannot export dirty volumes".

### PR DESCRIPTION
**Pull request by Rudd-O**
Fix for https://github.com/QubesOS/qubes-issues/issues/7325 .

Fixed my issue cloning the template.

### CODE REVIEW

**Comment by Rudd-O** [comment]
By the way I tested this on my local machine.

**Comment by marmarek** [comment]
pylint:
```
qubes/storage/file.py:63:0: C0301: Line too long (81/80) (line-too-long)
```
...

**Comment by Rudd-O** [comment]
Fixed.

**Comment by marmarek** [comment]
Can you add some simple unit test? Like checking on an fully-sparse file, and on another one with some data written.

**Comment by marmarek** [comment]
PipelineRefresh

**Review by marmarek — APPROVED** [review]

**Pull request merged**
