### PR TITLE
Add missing await in clone_disk_files() and other fixes

### PR DESCRIPTION
**Pull request by marmarek**

### CODE REVIEW

**Comment by marmarek** [comment]
Thanks @rustybird for https://github.com/QubesOS/qubes-core-admin/pull/418 !

**Comment by DemiMarie** [comment]
Could this be the reason for #399 having problems?

**Comment by marmarek** [comment]
> Could this be the reason for #399 having problems?

The most recent run was with this already included.

**Comment by DemiMarie** [comment]
> > Could this be the reason for #399 having problems?
> 
> The most recent run was with this already included.

Gotcha, thanks!

**Comment by marmarek** [comment]
> The most recent run was with this already included.

Hint: if you click into the openQA job's settings, there is `PULL_REQUESTS` option, with a list of included PRs. It is not easily clickable (the whole list is one big link :/) but it's useful anyway.

**Pull request merged**
