### PR TITLE
Adjust qubesd.service ordering once more

### PR DESCRIPTION
**Pull request by marmarek**
Order it after lvm2-activation.service, so that all present groups are
already activated (and its list can be cached).

### CODE REVIEW

**Comment by marmarek** [comment]
This won't work, as LVM activation is event based (doesn't use lvm2-activation-generator anymore). The event-generated unit looks like this:
```
# /run/systemd/transient/lvm-activate-qubes_dom0.service
# This is a transient unit file, created programmatically via the systemd API. Do not edit.
[Unit]
Description=/usr/sbin/lvm vgchange -aay --autoactivation event qubes_dom0
DefaultDependencies=no
[Service]
ExecStart=
ExecStart="/usr/sbin/lvm" "vgchange" "-aay" "--autoactivation" "event" "qubes_dom0"
# /usr/lib/systemd/system/service.d/10-timeout-abort.conf
# This file is part of the systemd package.
# See https://fedoraproject.org/wiki/Changes/Shorter_Shutdown_Timer.
#
# To facilitate debugging when a service fails to stop cleanly, 
# TimeoutStopFailureMode=abort is set to "crash" services that fail to stop in 
# the time allotted. This will cause the service to be terminated with SIGABRT 
# and a coredump to be generated.
#
# To undo this configuration change, create a mask file:
#   sudo mkdir -p /etc/systemd/system/service.d
#   sudo ln -sv /dev/null /etc/systemd/system/service.d/10-timeout-abort.conf
[Service]
TimeoutStopFailureMode=abort
```
Note there is no common `Before=` point to order. And it even has `DefaultDependencies=no`. It looks like systemd ordering can't solve this problem, we'll need a solution inside qubesd :/

**Comment by DemiMarie** [comment]
I think qubesd needs to not assume that every volume in a pool is active.  That’s a good idea anyway for performance reasons.  The current assumption is technical debt that needs to be paid off.

**Comment by marmarek** [comment]
I don't consider it a technical debt, there are many benefits of keeping volumes activated all the time. In my experiments the major disadvantage of activating on demand is inability to check its size/usage (LVM does not show this info for inactive volumes). But also, in my experiment with activating on demand (#382 ) it turns out there is _a lot more_ corner cases and potential for various race conditions (since you can't use /dev/ file existence anymore, and calling lvm each time is _slow_, you need to rely on the cache much more). And at the same time, it's very unclear if there are any benefits from this approach (some rough tests shows it isn't significantly faster, if at all) - it looks just like extra complexity...

**Comment by DemiMarie** [comment]
> And at the same time, it's very unclear if there are any benefits from this approach (some rough tests shows it isn't significantly faster, if at all) - it looks just like extra complexity...

How many volumes were active in these tests?

**Comment by marmarek** [comment]
AFAIR I did that on a test system with 100+ VMs

**Pull request merged**
